### PR TITLE
Add automated Docker image build

### PR DESCRIPTION
**Pull request by jshoughtaling**
This PR creates a Docker image using the [Dockerfile](https://github.com/chorus-ai/privacy_scan_tool/blob/main/Dockerfile) added by @Luyaochen1. The image gets pushed to the chorus-ai GHCR and is affiliated with the repository.

### CODE REVIEW

**Comment by Luyaochen1** [comment]
The build log seems good, but I am not able to access the package

ghcr.io/chorus-ai/chorus-privacy:main



Is it the right location, and do I need to be granted permission to
download it?


Luyao

**Comment by jshoughtaling** [comment]
@Luyaochen1 - hmm, that seems strange.

I'm able to pull the image without any authentication with the following command:

```
sudo docker pull ghcr.io/chorus-ai/chorus-privacy:main
```

Do you get a authentication error when running the command above? Or are you perhaps trying to pull on an ARM architecture?

**Comment by jshoughtaling** [comment]
@Luyaochen1 - I just confirmed that the image is public. Can you try to pull it again?

**Comment by Luyaochen1** [comment]
i can get it now. Very strange. Maybe we need to wait a while.

Here is screen log.

$ sudo docker pull ghcr.io/chorus-ai/chorus-privacy:main

Error response from daemon: denied.                         <= This is the
error

$ sudo docker pull ghcr.io/chorus-ai/chorus-privacy:main

main: Pulling from chorus-ai/chorus-privacy

c6cf28de8a06: Already exists

891494355808: Already exists

6582c62583ef: Already exists

bf2c3e352f3d: Already exists

a99509a32390: Already exists

.....

**Comment by Luyaochen1** [comment]
By the way. I tested the package, and it works well.

**Pull request merged**
